# 配置程序相关的设置
server:
  port: 8091
  servlet:
    context-path: /spring-boot-druuid
# 配置数据库的连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.31.7.33:3306/mydatabase
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      soft-min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true


